// This file is automatically generated. Do not modify it manually.

package main

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "mattermost-profanity-filter",
	Version: "1.0.0",
}
